calcu_cstat <- function
### function for calculating the c stat
(eset, 
 ### number of patients in the test set 
 Sj
 ### risk score of patients generated by other functions
){
  count <- 0 
  count1 <- 0 
  Yj <- as.numeric(as.character(pData(eset)[, "dmfs.time"]))
  Sj <- as.numeric(Sj[, 1])
  for(a in 1:length(Sj)){
    for(b in 1:length(Sj)){
      if((!is.na(Yj[a])) & (!is.na(Yj[b]))) {
        if(Yj[a] < Yj[b]) count <- count + 1
        if(Yj[a] < Yj[b] & Sj[a] > Sj[b]) count1 <- count1 + 1
      }
    }
  }
  if(count > 0 & count1 > 0) result <- count1 / count
  else result <- 0
  return(result)
  ### returns c statistics
}